DATN_MobileShop/DATN_MobileShop/Controllers/ProductController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopMobile_core.Common;
using WebShopMobile_core.Models;

namespace DATN_MobileShop.Controllers
{
    public class ProductController : Controller
    {
        private ShopMobileDB db = new ShopMobileDB();

        // GET: Product
        public ActionResult Index(string sortOrder, string searchstring, string currentFilter, int? page)
        {
            //các biến sắp xếp
            ViewBag.CurrentSort = sortOrder;//biến lấy yêu cầu sắp xếp hiện tại
            ViewBag.saptheogiatang = sortOrder == "gia" ? "" : "gia";
            ViewBag.saptheogiagiam = sortOrder == "gia_desc" ? "" : "gia_desc";
            ViewBag.saptheogia100_300 = sortOrder == "gia100_300" ? "" : "gia100_300";
            ViewBag.saptheogia300_500 = sortOrder == "gia300_500" ? "" : "gia300_500";
            ViewBag.saptheogia500_700 = sortOrder == "gia500_700" ? "" : "gia500_700";
            ViewBag.saptheogia700 = sortOrder == "gia700" ? "" : "gia700";

            ViewBag.iphone = sortOrder == "iphone" ? "" : "iphone";
            ViewBag.samsung = sortOrder == "samsung" ? "" : "samsung";
            ViewBag.oppo = sortOrder == "oppo" ? "" : "oppo";
            ViewBag.vivo = sortOrder == "vivo" ? "" : "vivo";


            ViewBag.sanphamnoibat = sortOrder == "sanphamnoibat" ? "" : "sanphamnoibat";
            ViewBag.sanphammoi = sortOrder == "sanphammoi" ? "" : "sanphammoi";
            ViewBag.thoiluongpin = sortOrder == "thoiluongpin" ? "" : "thoiluongpin";
            ViewBag.gaming = sortOrder == "gaming" ? "" : "gaming";
            ViewBag.tacvucoban = sortOrder == "tacvucoban" ? "" : "tacvucoban";
            ViewBag.camera = sortOrder == "camera" ? "" : "camera";
            ViewBag.manhinh = sortOrder == "manhinh" ? "" : "manhinh";

            //ViewBag.saptheogiagiam = sortOrder == "gia_desc";
            //Lấy giá trị bộ lọc dữ liệu hiện tại
            if (searchstring != null)
            {
                page = 1;//trang đầu tiên
            }
            else
            {
                searchstring = currentFilter;
            }
            ViewBag.CurrentFilter = searchstring;

            //lấy danh sách hàng
            var product = db.Product.Where(n=>n.id_category!=3).Select(s => s);
            //lọc theo tên hàng
            if (!String.IsNullOrEmpty(searchstring))
            {
                product = product.Where(p => p.productName.Contains(searchstring));
            }
            //sắp xếp
            switch (sortOrder)
            {
                case "gia":
                    product = product.OrderBy(s => s.price);
                    break;
                case "gia_desc":
                    product = product.OrderByDescending(s => s.price);
                    break;
                case "gia100_300":
                    product = product.Where(s => s.price >= 1000000 && s.price <= 2000000).OrderBy(s => s.productName);
                    break;
                case "gia300_500":
                    product = product.Where(s => s.price >= 3000000 && s.price <= 5000000).OrderBy(s => s.productName);
                    break;
                case "gia500_700":
                    product = product.Where(s => s.price >= 5000000 && s.price <= 7000000).OrderBy(s => s.productName);
                    break;
                case "gia700":
                    product = product.Where(s => s.price >= 7000000).OrderBy(s => s.productName);
                    break;
                case "iphone":
                    product = product.Where(s => s.id_category == 1).OrderBy(s => s.id);
                    break;
                case "samsung":
                    product = product.Where(s => s.id_category == 2).OrderBy(s => s.id);
                    break;
                case "oppo":
                    product = product.Where(s => s.id_category == 3).OrderBy(s => s.id);
                    break;
                case "vivo":
                    product = product.Where(s => s.id_category == 4).OrderBy(s => s.id);
                    break;
                default:
                    product = product.OrderBy(s => s.id);
                    break;
            }
            
            int pageSize = 8;
            int PageNumber = (page ?? 1);//nếu page bằng Null thì trả về 1
            return View(product.ToPagedList(PageNumber, pageSize));
        }

        public ActionResult Product_search(string sortOrder, int? page)
        {
            List<Product> products = db.Product.ToList();
            List<Product_detail> product_Details = db.Product_detail.ToList();
            var product_detail = from p in products
                                 join pd in product_Details on p.id equals pd.id_product into table1
                                 from pd in table1.DefaultIfEmpty()
                                 where p.id_category != 3
                                 select new Products
                                 {
                                     product = p,
                                     product_Detail = pd,

                                 };
            ViewBag.sanphamnoibat = sortOrder == "sanphamnoibat" ? "" : "sanphamnoibat";
            ViewBag.gaming = sortOrder == "gaming" ? "" : "gaming";
            ViewBag.tacvucoban = sortOrder == "tacvucoban" ? "" : "tacvucoban";
            ViewBag.manhinh = sortOrder == "manhinh" ? "" : "manhinh";
            ViewBag.camera = sortOrder == "camera" ? "" : "camera";
            ViewBag.sanphammoi = sortOrder == "sanphammoi" ? "" : "sanphammoi";
            ViewBag.thoiluongpin = sortOrder == "thoiluongpin" ? "" : "thoiluongpin";
            ViewBag.Ram = sortOrder == "Ram" ? "" : "Ram";
            ViewBag.Rom = sortOrder == "Rom" ? "" : "Rom";
            //ViewBag.thoiluongpin = sortOrder == "thoiluongpin" ? "" : "thoiluongpin";
            //sắp xếp
            switch (sortOrder)
            {
                case "sanphamnoibat":
                    product_detail = product_detail.Where(n => n.product.id_category != 3).OrderByDescending(n => n.product_Detail.viewcount);
                    break;
                case "gaming":
                    product_detail = product_detail.Where(n => n.product.id_category != 3 && n.product_Detail.Ram > 6);
                    break;
                case "manhinh":
                    product_detail = product_detail.Where(n => n.product.id_category != 3 && n.product_Detail.Screen_size > 5);
                    break;
                case "tacvucoban":
                    product_detail = product_detail.Where(n => n.product.id_category != 3 && n.product_Detail.Ram <= 4 && n.product_Detail.Rom <= 32).OrderByDescending(n => n.product.id);
                    break;
                case "camera":
                    product_detail = product_detail.Where(n => n.product.id_category != 3 && n.product_Detail.Camera_rear > 15 && n.product_Detail.front_camera > 20).OrderByDescending(n => n.product.id);
                    break;
                case "sanphammoi":
                    product_detail = product_detail.Where(n => n.product.id_category != 3).OrderByDescending(n => n.product.id).Take(12);
                    break;
                case "thoiluongpin":
                    product_detail = product_detail.Where(n => n.product.id_category != 3 && n.product_Detail.battery_capacity > 4500).OrderByDescending(n => n.product.id);
                    break;
                case "Ram":
                    product_detail = product_detail.OrderByDescending(n => n.product_Detail.Ram);
                    break;

                default:
                    product_detail = product_detail.OrderByDescending(s => s.product.id);
                    break;
            }
            int pageSize = 10;
            int PageNumber = (page ?? 1);//nếu page bằng Null thì trả về 1
            return View(product_detail.ToPagedList(PageNumber, pageSize));
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DATN_MobileShop/DATN_MobileShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="eCommerce HTML Template Free Download" name="keywords">
    <meta content="eCommerce HTML Template Free Download" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

    <!-- CSS Libraries -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="~/wwwroot/lib/slick/slick.css" rel="stylesheet">
    <link href="~/wwwroot/lib/slick/slick-theme.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/wwwroot/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Top bar Start -->
    <div class="top-bar">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <i class="fa fa-envelope"></i>
                    support@email.com
                </div>
                <div class="col-sm-6">
                    <i class="fa fa-phone-alt"></i>
                    +012-345-6789
                </div>
            </div>
        </div>
    </div>
    <!-- Top bar End -->
    <!-- Nav Bar Start -->
    <div class="nav">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                <a href="#" class="navbar-brand">MENU</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto">
                        <a href=@Url.Action("Index","Home") class="nav-item nav-link active">Trang chủ</a>
                        <a href=@Url.Action("Index","Product") class="nav-item nav-link">Sản phẩm</a>                
                        <a 
                           @if (Session["Giohang"] == null) { @Url.Action("CartNull","Cart")}
                           href=@Url.Action("Giohang","Cart") class="nav-item nav-link">Giỏ hàng</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Trang khác</a>
                            <div class="dropdown-menu">
                                <a href="wishlist.html" class="dropdown-item">Bảo hành</a>
                                <a href=@Url.Action("Login","Customers") class="dropdown-item">Đăng kí & Đăng nhập</a>
                                <a href="contact.html" class="dropdown-item">Blog</a>
                            </div>
                        </div>
                    </div>
                    <div class="navbar-nav ml-auto">
                        <div class="nav-item dropdown">
                            @{
                                var ss = Session["Taikhoan"];
                                if (ss == null)
                                {
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Tài Khoản</a>
                                    <div class="dropdown-menu">

                                        <a href=@Url.Action("Login", "Customers") class="nav-item nav-link">Đăng nhập</a>
                                        <a href=@Url.Action("Register", "Customers") class="nav-item nav-link">Đăng kí</a>

                                    </div>
                                }
                                else
                                {
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">@Session["username"]</a>
                                    <div class="dropdown-menu">
                                        <a href=@Url.Action("Logout", "Customers") class="nav-item nav-link">Đăng xuất</a>
                                        <a href="/User/Details/" class="nav-item nav-link">Cài đặt</a>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Nav Bar End -->
    <!-- Bottom Bar Start -->
    <div class="bottom-bar">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-md-3">
                    <div class="logo">
                        <a href="index.html">
                            <img src="~/wwwroot/img/logo.png" alt="Logo">
                        </a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="search">
                        @using (Html.BeginForm("Index", "Product"))
                        {
                            <input type="text" placeholder="Tìm kiếm" , name="searchstring" @ViewBag.CurrentFilter as string>

                            <button><i class="fa fa-search"></i></button>
                        }
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="user">
                        <a href="wishlist.html" class="btn wishlist">
                            <i class="fa fa-heart"></i>
                            <span>(0)</span>
                        </a>
                        <a href="/Cart/Giohang/" class="btn cart">
                            <i class="fa fa-shopping-cart"></i>
                            <span>@Session["tongsoluong"]</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bottom Bar End -->
    @RenderBody()
    <!-- Footer Start -->
    <div class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Liên hệ với chúng tôi</h2>
                        <div class="contact-info">
                            <p><i class="fa fa-map-marker"></i>78, Đường Láng, Cầu Giấy, Hà Nội</p>
                            <p><i class="fa fa-envelope"></i>thegioidienthoai@gmail.com</p>
                            <p><i class="fa fa-phone"></i>+123-456-7890</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Theo dõi ngay</h2>
                        <div class="contact-info">
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Thông tin về công ty</h2>
                        <ul>
                            <li><a href="#">Thông tin cửa hàng</a></li>
                            <li><a href="#">Thông tin bảo hành</a></li>
                            <li><a href="#">Cách thức thanh toán</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <h2>Chính sách</h2>
                        <ul>
                            <li><a href="#">Đổi trả</a></li>
                            <li><a href="#">Bảo hành</a></li>
                            <li><a href="#">Sửa chữa</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <!-- <div class="row payment align-items-center">
                 <div class="col-md-6">
                     <div class="payment-method">
                         <h2>We Accept:</h2>
                         <img src="img/payment-method.png" alt="Payment Method" />
                     </div>
                 </div>
                 <div class="col-md-6">
                     <div class="payment-security">
                         <h2>Secured By:</h2>
                         <img src="img/godaddy.svg" alt="Payment Security" />
                         <img src="img/norton.svg" alt="Payment Security" />
                         <img src="img/ssl.svg" alt="Payment Security" />
                     </div>
                 </div>
             </div>-->
        </div>
    </div>
    <!-- Footer End -->
    <!-- Footer Bottom Start -->
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-6 copyright">
                    <p>Copyright &copy; <a href="https://htmlcodex.com">Phạm Văn Nguyên</a>. All Rights Reserved</p>
                </div>

                <div class="col-md-6 template-by">
                    <p> <a href="https://htmlcodex.com">Đồ án tốt nghiệp</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Bottom End -->
    <!-- Back to Top -->
    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/wwwroot/lib/easing/easing.min.js"></script>
    <script src="~/wwwroot/lib/slick/slick.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/wwwroot/js/main.js"></script>
</body>
</html>