DATN_MobileShop/DATN_MobileShop/Areas/Admin/Controllers/AdvantismentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopMobile_core.Models;

namespace DATN_MobileShop.Areas.Admin.Controllers
{
    public class AdvantismentsController : BaseController
    {
        private ShopMobileDB db = new ShopMobileDB();

        // GET: Admin/Advantisments
        public ActionResult Index()
        {
            var advantisment = db.Advantisment.Include(a => a.Product);
            return View(advantisment.ToList());
        }

        // GET: Admin/Advantisments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advantisment advantisment = db.Advantisment.Find(id);
            if (advantisment == null)
            {
                return HttpNotFound();
            }
            return View(advantisment);
        }

        // GET: Admin/Advantisments/Create
        public ActionResult Create()
        {
            ViewBag.id_product = new SelectList(db.Product, "id", "productName");
            return View();
        }

        // POST: Admin/Advantisments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,id_product,photo,statuss,posision,create_date")] Advantisment advantisment)
        {
            if (ModelState.IsValid)
            {
                advantisment.photo = " ";
                var f = Request.Files["ImageFile"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Server.MapPath("~/wwwroot/img/" + FileName);
                    f.SaveAs(UploadPath);
                    advantisment.photo = FileName;
                }
                advantisment.create_date = DateTime.Now;
                db.Advantisment.Add(advantisment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_product = new SelectList(db.Product, "id", "productName", advantisment.id_product);
            return View(advantisment);
        }

        // GET: Admin/Advantisments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advantisment advantisment = db.Advantisment.Find(id);
            if (advantisment == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_product = new SelectList(db.Product, "id", "productName", advantisment.id_product);
            return View(advantisment);
        }

        // POST: Admin/Advantisments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,id_product,photo,statuss,texts,posision,create_date,update_date")] Advantisment advantisment)
        {
            if (ModelState.IsValid)
            {
                advantisment.photo = " ";
                var f = Request.Files["ImageFile"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Server.MapPath("~/wwwroot/img/" + FileName);
                    f.SaveAs(UploadPath);
                    advantisment.photo = FileName;
                }
                advantisment.update_date = DateTime.Now;
                db.Entry(advantisment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_product = new SelectList(db.Product, "id", "productName", advantisment.id_product);
            return View(advantisment);
        }

        // GET: Admin/Advantisments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advantisment advantisment = db.Advantisment.Find(id);
            if (advantisment == null)
            {
                return HttpNotFound();
            }
            return View(advantisment);
        }

        // POST: Admin/Advantisments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Advantisment advantisment = db.Advantisment.Find(id);
            db.Advantisment.Remove(advantisment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Controllers/HomeAdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DATN_MobileShop.Areas.Admin.Controllers
{
    public class HomeAdController : BaseController
    {
        // GET: Admin/HomeAd
        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login", "LoginAd");
        }
    }
}

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Views/Advantisments/Create.cshtml
@model WebShopMobile_core.Models.Advantisment

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Quản lý Quảng Cáo
        <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-dashboard"></i>@Html.ActionLink("Home", "Index", "HomeAd")</li>
        <li class="active">Tạo mới quảng cáo</li>
    </ol>
</section>

@using (Html.BeginForm("create", "Advantisments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Advantisment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_product, "Sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_product", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo, "Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img id="output" class="img-rounded" alt="Ảnh" width="400" height="200" src="~/wwwroot/h0.png" />
                <p><label for="ufile" style="cursor: pointer">Chọn file ảnh</label></p>
                <input name="ImageFile" id="ufile" type="file" style="display: none" onchange="loadFile(event)" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.statuss, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.statuss)
                    @Html.ValidationMessageFor(model => model.statuss, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.posision, "Vị trí", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.posision, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.posision, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>
<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Views/Advantisments/Delete.cshtml
@model WebShopMobile_core.Models.Advantisment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Advantisment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.statuss)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.statuss)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.texts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.texts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.posision)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.posision)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.create_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.create_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.update_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.update_date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Views/Advantisments/Details.cshtml
@model WebShopMobile_core.Models.Advantisment

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Advantisment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.statuss)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.statuss)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.texts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.texts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.posision)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.posision)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.create_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.create_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.update_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.update_date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Views/Advantisments/Edit.cshtml
@model WebShopMobile_core.Models.Advantisment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var ImagePath = "~/wwwroot/img/" + Model.photo;
}

<section class="content-header">
    <h1>
        Quản lý sản phẩm
        <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-dashboard"></i>@Html.ActionLink("Trang chủ", "Index", "HomeAd")</li>
        <li class="active">Quảng cáo</li>
    </ol>
</section>

@using (Html.BeginForm("Edit", "Advantisments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Advantisment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.id_product, "Sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_product", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo, "Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="@Url.Content(@ImagePath)" />
                <p><label for="ufile" style="cursor: pointer">Chọn file ảnh</label></p>
                <input name="ImageFile" id="ufile" type="file" style="display: none" onchange="loadFile(event)" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.statuss, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.statuss)
                    @Html.ValidationMessageFor(model => model.statuss, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.posision, "vị trí", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.posision, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.posision, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>
<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Views/Advantisments/Index.cshtml
@model IEnumerable<WebShopMobile_core.Models.Advantisment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<style type='text/css'>
    table {
        counter-reset: rowNumber;
    }

    .stt {
        counter-increment: rowNumber;
    }

    table tr td:first-child::before {
        content: counter(rowNumber);
        min-width: 1em;
        margin-right: 0.5em;
    }
</style>
<p>
    <a href="/Admin/Advantisments/Create" class="btn btn-success btn-lg active btn-sm" role="button" aria-pressed="true">Thêm mới</a>
</p>
<table class="table">
    <tr>
        <th>
            Số thứ tự
        </th>
        <th>
            Tên sản phẩm
        </th>
        <th>
            Hình ảnh
        </th>
        <th>
            Trạng thái
        </th>      
        <th>
            Vị trí
        </th>
        <th>
            Ngày tạo
        </th>
        <th>
            Cập nhật
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr class="stt">
        <td>
            
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.productName)
        </td>
        <td>
            @{
                // lấy đường dẫn file ảnh
                string ImagePath = "~/wwwroot/img/" + item.photo;
            }
            <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.statuss)
        </td>     
        <td>
            @Html.DisplayFor(modelItem => item.posision)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.create_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.update_date)
        </td>
        <td>
            <a href="/Admin/Advantisments/Edit/@item.id" class="btn btn-success btn-lg active btn-sm" role="button" aria-pressed="true">Sửa</a>
            <a href="/Admin/Advantisments/Delete/@item.id" class="btn btn-success btn-lg active btn-sm" role="button" aria-pressed="true">Xóa</a>
        </td>
    </tr>
}

</table>