DATN_MobileShop/DATN_MobileShop/Areas/Admin/Controllers/Carts1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopMobile_core.Common;
using WebShopMobile_core.Models;

namespace DATN_MobileShop.Areas.Admin.Controllers
{
    public class Carts1Controller : BaseController
    {
        private ShopMobileDB db = new ShopMobileDB();
        // GET: Admin/Carts1
        public ActionResult Index()
        {
            var carts = db.Carts.Include(c => c.Customer).Include(c => c.Customer1).Include(c => c.Voucher);               
            return View(carts.ToList());
        }  
     
        // GET: Admin/Carts1/Details/5
        public ActionResult Details(int? id)
        {        
            var cart_Details = db.Cart_Details.Include(c => c.Carts).Include(c => c.Product).Where(a => a.id_cart == id);
            double iTongtien = 0;
            iTongtien = (double)cart_Details.Sum(n => n.price);
            ViewBag.Tongtien = iTongtien;
            return View(cart_Details.ToList());
        }

        // GET: Admin/Carts1/Create
        public ActionResult Create()
        {
            ViewBag.id_custommer = new SelectList(db.Customer, "id", "fullname");
            ViewBag.id_voucher = new SelectList(db.Voucher, "id", "code");
            return View();
        }

        // POST: Admin/Carts1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,id_voucher,id_custommer,create_date,update_at,statuss,total,payment,address")] Carts carts)
        {
            if (ModelState.IsValid)
            {
                db.Carts.Add(carts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_custommer = new SelectList(db.Customer, "id", "fullname", carts.id_custommer);
            //ViewBag.id_custommer = new SelectList(db.Customer, "id", "fullname", carts.id_custommer);
            ViewBag.id_voucher = new SelectList(db.Voucher, "id", "code", carts.id_voucher);
            return View(carts);
        }

        // GET: Admin/Carts1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carts carts = db.Carts.Find(id);
            if (carts == null)
            {
                return HttpNotFound();
            }
            /*ViewBag.id_custommer = new SelectList(db.Customer, "id", "fullname", carts.id_custommer);
            ViewBag.id_custommer = new SelectList(db.Customer, "id", "fullname", carts.id_custommer);
            ViewBag.id_voucher = new SelectList(db.Voucher, "id", "code", carts.id_voucher);*/           
            return View(carts);
        }

        // POST: Admin/Carts1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,id_voucher,id_custommer,create_date,update_at,statuss,total,payment,address")] Carts carts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(carts).State = EntityState.Modified;               
                if(carts.payment == true)
                {
                    var cart_Details = db.Cart_Details.Where(p => p.id_cart == carts.id);
                    foreach (var item in cart_Details)
                    {
                        Product_detail product_Detail = db.Product_detail.Where(p => p.id_product == item.id_product).FirstOrDefault();
                        product_Detail.quantily -= item.quanity;
                        product_Detail.viewcount += item.quanity;
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_custommer = new SelectList(db.Customer, "id", "fullname", carts.id_custommer);
            ViewBag.id_voucher = new SelectList(db.Voucher, "id", "code", carts.id_voucher);
            return View(carts);
        }

        // GET: Admin/Carts1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carts carts = db.Carts.Find(id);
            if (carts == null)
            {
                return HttpNotFound();
            }
            return View(carts);
        }

        // POST: Admin/Carts1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var cart_detail = db.Cart_Details.Where(n => n.id_cart == id).FirstOrDefault();
            if (cart_detail != null)
            {
                db.Cart_Details.Remove(cart_detail);
                db.SaveChanges();
            }
            Carts carts = db.Carts.Find(id);
            db.Carts.Remove(carts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Controllers/HomeAdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DATN_MobileShop.Areas.Admin.Controllers
{
    public class HomeAdController : BaseController
    {
        // GET: Admin/HomeAd
        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login", "LoginAd");
        }
    }
}

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Controllers/ReportsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopMobile_core.Common;
using WebShopMobile_core.Models;

namespace DATN_MobileShop.Areas.Admin.Controllers
{
    public class ReportsController : Controller
    {
        // GET: Admin/Report
        private ShopMobileDB db = new ShopMobileDB();
        public ActionResult Index(string sortOrder, string searchstring, string currentFilter, int? page, string from_date, string to_date)
        {

            List<Product> products = db.Product.ToList();
            List<Product_detail> product_Details = db.Product_detail.ToList();
            List<Carts> carts = db.Carts.ToList();
            List<Cart_Details> cart_Details = db.Cart_Details.ToList();
            var thongke = from p in cart_Details
                          join pd in product_Details on p.id_product equals pd.id_product into table1
                          join cd in products on p.id_product equals cd.id into table2
                          join c in carts on p.id_cart equals c.id into table3
                          from pd in table1.DefaultIfEmpty()
                          from cd in table2.DefaultIfEmpty()
                          from c in table3
                          where cd.id_category != 3
                          select new Products
                          {
                              product = cd,
                              product_Detail = pd,
                              carts = c
                          };
            ViewBag.iphone = sortOrder == "iphone" ? "" : "iphone";
            ViewBag.samsung = sortOrder == "samsung" ? "" : "samsung";
            ViewBag.oppo = sortOrder == "oppo" ? "" : "oppo";
            ViewBag.vivo = sortOrder == "vivo" ? "" : "vivo";

            //Lấy giá trị bộ lọc dữ liệu hiện tại
            if (searchstring != null)
            {
                page = 1;//trang đầu tiên
            }
            else
            {
                searchstring = currentFilter;
            }
            ViewBag.CurrentFilter = searchstring;
            ViewBag.from_date = from_date;
            ViewBag.to_date = to_date;

            //lọc theo tên hàng
            if (!String.IsNullOrEmpty(searchstring))
            {
                thongke = thongke.Where(p => p.product.productName.Contains(searchstring));
            }

            if (!String.IsNullOrEmpty(from_date) && !String.IsNullOrEmpty(to_date))
            {
                DateTime from = DateTime.Parse(from_date);
                DateTime to = DateTime.Parse(to_date);
                thongke = thongke.Where(p => p.carts.create_date >= from && p.carts.create_date <=to);

            }
           

            //sắp xếp
            switch (sortOrder)
            {
                case "iphone":
                    thongke = thongke.Where(n => n.product.id_category == 1).OrderByDescending(n => n.carts.create_date);
                    break;
                case "samsung":
                    thongke = thongke.Where(n => n.product.id_category == 2).OrderByDescending(n => n.carts.create_date);
                    break;
                case "oppo":
                    thongke = thongke.Where(n => n.product.id_category == 4).OrderByDescending(n => n.carts.create_date);
                    break;
                case "vivo":
                    thongke = thongke.Where(n => n.product.id_category == 5).OrderByDescending(n => n.carts.create_date);
                    break;
                case "productNew":
                    thongke = thongke.Where(n => n.product.id_category == 3).OrderByDescending(n => n.carts.create_date);
                    break;
                default:
                    thongke = thongke.OrderByDescending(s => s.carts.create_date);
                    break;
            }
            int pageSize = 10;
            int PageNumber = (page ?? 1);//nếu page bằng Null thì trả về 1
            return View(thongke.ToPagedList(PageNumber, pageSize));
        }
    }
}

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Controllers/colorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopMobile_core.Models;

namespace DATN_MobileShop.Areas.Admin.Controllers
{
    public class colorsController : BaseController
    {
        private ShopMobileDB db = new ShopMobileDB();

        // GET: Admin/colors
        public ActionResult Index()
        {
            return View(db.color.ToList());
        }

        // GET: Admin/colors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            color color = db.color.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // GET: Admin/colors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/colors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,color_name")] color color)
        {
            if (ModelState.IsValid)
            {
                db.color.Add(color);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(color);
        }

        // GET: Admin/colors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            color color = db.color.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // POST: Admin/colors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,color_name")] color color)
        {
            if (ModelState.IsValid)
            {
                db.Entry(color).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(color);
        }

        // GET: Admin/colors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            color color = db.color.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // POST: Admin/colors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            color color = db.color.Find(id);
            db.color.Remove(color);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Areas/Admin/Assets/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Areas/Admin/Assets/css/_all-skins.min.css">
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <script src="~/Areas/Admin/Plugin/ckfinder/ckfinder.js"></script>
    <script src="~/Areas/Admin/Plugin/ckeditor/ckeditor.js"></script>
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>A</b>LT</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Admin</b>LTE</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/Areas/Admin/Assets/images/user2-160x160.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">@Session["FullName"]</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="~/Areas/Admin/Assets/images/user2-160x160.jpg" class="img-circle" alt="User Image">

                                    <p>
                                        @Session["FullName"]
                                        <small>Web developer</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="@Url.Action("Logout","HomeAd")" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/Areas/Admin/Assets/images/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>@Session["FullName"]</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- sidebar menu: : style can be found in sidebar.less -->
                @{
                    Html.RenderPartial("_Navbar");
                }
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
         
            <section>
                <div class=" container-fluid" style="background: white ">
                    @if (TempData["AlertMessage"] != null)
                    {
                        <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                            @TempData["AlertMessage"]
                        </div>
                    }
                    @RenderBody()
                </div>

            </section>
            
            <!-- /.content -->
        </div>
        <!-- Content Header (Page header) -->
      
        <!-- /.content-wrapper -->
        
        <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/Areas/Admin/Assets/js/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Areas/Admin/Assets/js/jquery-ui.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Areas/Admin/Assets/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Areas/Admin/Assets/js/adminlte.min.js"></script>

    

    @RenderSection("scripts", false)
</body>
</html>

DATN_MobileShop/DATN_MobileShop/Areas/Admin/Views/Shared/_Navbar.cshtml
<ul class="sidebar-menu" data-widget="tree">
    <li class="header">LAOYOUT ADMIN</li>

    <li>
        <a href="@Url.Action("Index", "Product_category")">
            <i class="fa fa-th"></i> <span>Danh mục sản phẩm</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "colors")">
            <i class="fa fa-th"></i> <span>Quản lý Màu sắc</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Products")">
            <i class="fa fa-th"></i> <span>Quản lý sản phẩm</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Carts1")">
            <i class="fa fa-th"></i> <span>Quản lý đơn hàng</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "blog")">
            <i class="fa fa-th"></i> <span>Quản lý tin tức</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Advantisments")">
            <i class="fa fa-th"></i> <span>Quản lý Quảng cáo</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Customer")">
            <i class="fa fa-th"></i> <span>Quản lý Tài khoản Khách hàng</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Reports")">
            <i class="fa fa-th"></i> <span>Thống kê</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Admins")">
            <i class="fa fa-th"></i> <span>Tài khoản Admin</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Role")">
            <i class="fa fa-th"></i> <span>Quyền</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "GroupAdmin")">
            <i class="fa fa-th"></i> <span>Nhóm quyền</span>
        </a>
    </li>

</ul>